name: PR Check

on:
  pull_request:
    branches: [ main, master ]

jobs:
  version-check:
    name: Check VERSION file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if CHANGELOG.md file exists
        run: |
          if [ ! -f "CHANGELOG.md" ]; then
            echo "CHANGELOG.md file is missing. Please restore the file."
            exit 1
          fi

      - name: Check if VERSION file exists
        run: |
          if [ ! -f "VERSION" ]; then
            echo "VERSION file is missing. Please restore and update the VERSION file."
            exit 1
          fi

      - name: Check if VERSION has been modified
        run: |
          if ! git diff --name-only origin/${{ github.base_ref }} | grep -q "^VERSION$"; then
            echo "VERSION file was not modified in this PR. Please update the version."
            exit 1
          fi
          echo "VERSION file has been properly updated."

  check:
    name: PHP ${{ matrix.php-version }} Check
    runs-on: ubuntu-latest
    needs: version-check
    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4']
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run checks
        run: composer check
