name: Release

on:
  push:
    branches: [ main ]


jobs:
  verify_and_tag:
    runs-on: ubuntu-latest
    steps:
      - name: First interaction
        uses: actions/first-interaction@v1.3.0
                
